<template>
  <div class="flex-scroll-y" style="padding-right:5px;">
    <i style="font-size:32px;margin:10px;" class="icon-home" />
    <i style="font-size:32px;margin:10px;" class="icon-home2" />
    <i style="font-size:32px;margin:10px;" class="icon-home5" />
    <i style="font-size:32px;margin:10px;" class="icon-home7" />
    <i style="font-size:32px;margin:10px;" class="icon-home8" />
    <i style="font-size:32px;margin:10px;" class="icon-home9" />
    <i style="font-size:32px;margin:10px;" class="icon-office" />
    <i style="font-size:32px;margin:10px;" class="icon-city" />
    <i style="font-size:32px;margin:10px;" class="icon-newspaper" />
    <i style="font-size:32px;margin:10px;" class="icon-magazine" />
    <i style="font-size:32px;margin:10px;" class="icon-design" />
    <i style="font-size:32px;margin:10px;" class="icon-pencil" />
    <i style="font-size:32px;margin:10px;" class="icon-pencil3" />
    <i style="font-size:32px;margin:10px;" class="icon-pencil4" />
    <i style="font-size:32px;margin:10px;" class="icon-pencil5" />
    <i style="font-size:32px;margin:10px;" class="icon-pencil6" />
    <i style="font-size:32px;margin:10px;" class="icon-pencil7" />
    <i style="font-size:32px;margin:10px;" class="icon-eraser" />
    <i style="font-size:32px;margin:10px;" class="icon-eraser2" />
    <i style="font-size:32px;margin:10px;" class="icon-eraser3" />
    <i style="font-size:32px;margin:10px;" class="icon-quill2" />
    <i style="font-size:32px;margin:10px;" class="icon-quill4" />
    <i style="font-size:32px;margin:10px;" class="icon-pen" />
    <i style="font-size:32px;margin:10px;" class="icon-pen-plus" />
    <i style="font-size:32px;margin:10px;" class="icon-pen-minus" />
    <i style="font-size:32px;margin:10px;" class="icon-pen2" />
    <i style="font-size:32px;margin:10px;" class="icon-blog" />
    <i style="font-size:32px;margin:10px;" class="icon-pen6" />
    <i style="font-size:32px;margin:10px;" class="icon-brush" />
    <i style="font-size:32px;margin:10px;" class="icon-spray" />
    <i style="font-size:32px;margin:10px;" class="icon-color-sampler" />
    <i style="font-size:32px;margin:10px;" class="icon-toggle" />
    <i style="font-size:32px;margin:10px;" class="icon-bucket" />
    <i style="font-size:32px;margin:10px;" class="icon-gradient" />
    <i style="font-size:32px;margin:10px;" class="icon-eyedropper" />
    <i style="font-size:32px;margin:10px;" class="icon-eyedropper2" />
    <i style="font-size:32px;margin:10px;" class="icon-eyedropper3" />
    <i style="font-size:32px;margin:10px;" class="icon-droplet" />
    <i style="font-size:32px;margin:10px;" class="icon-droplet2" />
    <i style="font-size:32px;margin:10px;" class="icon-color-clear" />
    <i style="font-size:32px;margin:10px;" class="icon-paint-format" />
    <i style="font-size:32px;margin:10px;" class="icon-stamp" />
    <i style="font-size:32px;margin:10px;" class="icon-image2" />
    <i style="font-size:32px;margin:10px;" class="icon-image-compare" />
    <i style="font-size:32px;margin:10px;" class="icon-images2" />
    <i style="font-size:32px;margin:10px;" class="icon-image3" />
    <i style="font-size:32px;margin:10px;" class="icon-images3" />
    <i style="font-size:32px;margin:10px;" class="icon-image4" />
    <i style="font-size:32px;margin:10px;" class="icon-image5" />
    <i style="font-size:32px;margin:10px;" class="icon-camera" />
    <i style="font-size:32px;margin:10px;" class="icon-shutter" />
    <i style="font-size:32px;margin:10px;" class="icon-headphones" />
    <i style="font-size:32px;margin:10px;" class="icon-headset" />
    <i style="font-size:32px;margin:10px;" class="icon-music" />
    <i style="font-size:32px;margin:10px;" class="icon-album" />
    <i style="font-size:32px;margin:10px;" class="icon-tape" />
    <i style="font-size:32px;margin:10px;" class="icon-piano" />
    <i style="font-size:32px;margin:10px;" class="icon-speakers" />
    <i style="font-size:32px;margin:10px;" class="icon-play" />
    <i style="font-size:32px;margin:10px;" class="icon-clapboard-play" />
    <i style="font-size:32px;margin:10px;" class="icon-clapboard" />
    <i style="font-size:32px;margin:10px;" class="icon-media" />
    <i style="font-size:32px;margin:10px;" class="icon-presentation" />
    <i style="font-size:32px;margin:10px;" class="icon-movie" />
    <i style="font-size:32px;margin:10px;" class="icon-film" />
    <i style="font-size:32px;margin:10px;" class="icon-film2" />
    <i style="font-size:32px;margin:10px;" class="icon-film3" />
    <i style="font-size:32px;margin:10px;" class="icon-film4" />
    <i style="font-size:32px;margin:10px;" class="icon-video-camera" />
    <i style="font-size:32px;margin:10px;" class="icon-video-camera2" />
    <i style="font-size:32px;margin:10px;" class="icon-video-camera-slash" />
    <i style="font-size:32px;margin:10px;" class="icon-video-camera3" />
    <i style="font-size:32px;margin:10px;" class="icon-dice" />
    <i style="font-size:32px;margin:10px;" class="icon-chess-king" />
    <i style="font-size:32px;margin:10px;" class="icon-chess-queen" />
    <i style="font-size:32px;margin:10px;" class="icon-chess" />
    <i style="font-size:32px;margin:10px;" class="icon-megaphone" />
    <i style="font-size:32px;margin:10px;" class="icon-new" />
    <i style="font-size:32px;margin:10px;" class="icon-connection" />
    <i style="font-size:32px;margin:10px;" class="icon-station" />
    <i style="font-size:32px;margin:10px;" class="icon-satellite-dish2" />
    <i style="font-size:32px;margin:10px;" class="icon-feed" />
    <i style="font-size:32px;margin:10px;" class="icon-mic2" />
    <i style="font-size:32px;margin:10px;" class="icon-mic-off2" />
    <i style="font-size:32px;margin:10px;" class="icon-book" />
    <i style="font-size:32px;margin:10px;" class="icon-book2" />
    <i style="font-size:32px;margin:10px;" class="icon-book-play" />
    <i style="font-size:32px;margin:10px;" class="icon-book3" />
    <i style="font-size:32px;margin:10px;" class="icon-bookmark" />
    <i style="font-size:32px;margin:10px;" class="icon-books" />
    <i style="font-size:32px;margin:10px;" class="icon-archive" />
    <i style="font-size:32px;margin:10px;" class="icon-reading" />
    <i style="font-size:32px;margin:10px;" class="icon-library2" />
    <i style="font-size:32px;margin:10px;" class="icon-graduation2" />
    <i style="font-size:32px;margin:10px;" class="icon-file-text" />
    <i style="font-size:32px;margin:10px;" class="icon-profile" />
    <i style="font-size:32px;margin:10px;" class="icon-file-empty" />
    <i style="font-size:32px;margin:10px;" class="icon-file-empty2" />
    <i style="font-size:32px;margin:10px;" class="icon-files-empty" />
    <i style="font-size:32px;margin:10px;" class="icon-files-empty2" />
    <i style="font-size:32px;margin:10px;" class="icon-file-plus" />
    <i style="font-size:32px;margin:10px;" class="icon-file-plus2" />
    <i style="font-size:32px;margin:10px;" class="icon-file-minus" />
    <i style="font-size:32px;margin:10px;" class="icon-file-minus2" />
    <i style="font-size:32px;margin:10px;" class="icon-file-download" />
    <i style="font-size:32px;margin:10px;" class="icon-file-download2" />
    <i style="font-size:32px;margin:10px;" class="icon-file-upload" />
    <i style="font-size:32px;margin:10px;" class="icon-file-upload2" />
    <i style="font-size:32px;margin:10px;" class="icon-file-check" />
    <i style="font-size:32px;margin:10px;" class="icon-file-check2" />
    <i style="font-size:32px;margin:10px;" class="icon-file-eye" />
    <i style="font-size:32px;margin:10px;" class="icon-file-eye2" />
    <i style="font-size:32px;margin:10px;" class="icon-file-text2" />
    <i style="font-size:32px;margin:10px;" class="icon-file-text3" />
    <i style="font-size:32px;margin:10px;" class="icon-file-picture" />
    <i style="font-size:32px;margin:10px;" class="icon-file-picture2" />
    <i style="font-size:32px;margin:10px;" class="icon-file-music" />
    <i style="font-size:32px;margin:10px;" class="icon-file-music2" />
    <i style="font-size:32px;margin:10px;" class="icon-file-play" />
    <i style="font-size:32px;margin:10px;" class="icon-file-play2" />
    <i style="font-size:32px;margin:10px;" class="icon-file-video" />
    <i style="font-size:32px;margin:10px;" class="icon-file-video2" />
    <i style="font-size:32px;margin:10px;" class="icon-copy" />
    <i style="font-size:32px;margin:10px;" class="icon-copy2" />
    <i style="font-size:32px;margin:10px;" class="icon-file-zip" />
    <i style="font-size:32px;margin:10px;" class="icon-file-zip2" />
    <i style="font-size:32px;margin:10px;" class="icon-file-xml" />
    <i style="font-size:32px;margin:10px;" class="icon-file-xml2" />
    <i style="font-size:32px;margin:10px;" class="icon-file-css" />
    <i style="font-size:32px;margin:10px;" class="icon-file-css2" />
    <i style="font-size:32px;margin:10px;" class="icon-file-presentation" />
    <i style="font-size:32px;margin:10px;" class="icon-file-presentation2" />
    <i style="font-size:32px;margin:10px;" class="icon-file-stats" />
    <i style="font-size:32px;margin:10px;" class="icon-file-stats2" />
    <i style="font-size:32px;margin:10px;" class="icon-file-locked" />
    <i style="font-size:32px;margin:10px;" class="icon-file-locked2" />
    <i style="font-size:32px;margin:10px;" class="icon-file-spreadsheet" />
    <i style="font-size:32px;margin:10px;" class="icon-file-spreadsheet2" />
    <i style="font-size:32px;margin:10px;" class="icon-copy3" />
    <i style="font-size:32px;margin:10px;" class="icon-copy4" />
    <i style="font-size:32px;margin:10px;" class="icon-paste" />
    <i style="font-size:32px;margin:10px;" class="icon-paste2" />
    <i style="font-size:32px;margin:10px;" class="icon-paste3" />
    <i style="font-size:32px;margin:10px;" class="icon-paste4" />
    <i style="font-size:32px;margin:10px;" class="icon-stack" />
    <i style="font-size:32px;margin:10px;" class="icon-stack2" />
    <i style="font-size:32px;margin:10px;" class="icon-stack3" />
    <i style="font-size:32px;margin:10px;" class="icon-folder" />
    <i style="font-size:32px;margin:10px;" class="icon-folder-search" />
    <i style="font-size:32px;margin:10px;" class="icon-folder-download" />
    <i style="font-size:32px;margin:10px;" class="icon-folder-upload" />
    <i style="font-size:32px;margin:10px;" class="icon-folder-plus" />
    <i style="font-size:32px;margin:10px;" class="icon-folder-plus2" />
    <i style="font-size:32px;margin:10px;" class="icon-folder-minus" />
    <i style="font-size:32px;margin:10px;" class="icon-folder-minus2" />
    <i style="font-size:32px;margin:10px;" class="icon-folder-check" />
    <i style="font-size:32px;margin:10px;" class="icon-folder-heart" />
    <i style="font-size:32px;margin:10px;" class="icon-folder-remove" />
    <i style="font-size:32px;margin:10px;" class="icon-folder2" />
    <i style="font-size:32px;margin:10px;" class="icon-folder-open" />
    <i style="font-size:32px;margin:10px;" class="icon-folder3" />
    <i style="font-size:32px;margin:10px;" class="icon-folder4" />
    <i style="font-size:32px;margin:10px;" class="icon-folder-plus3" />
    <i style="font-size:32px;margin:10px;" class="icon-folder-minus3" />
    <i style="font-size:32px;margin:10px;" class="icon-folder-plus4" />
    <i style="font-size:32px;margin:10px;" class="icon-folder-minus4" />
    <i style="font-size:32px;margin:10px;" class="icon-folder-download2" />
    <i style="font-size:32px;margin:10px;" class="icon-folder-upload2" />
    <i style="font-size:32px;margin:10px;" class="icon-folder-download3" />
    <i style="font-size:32px;margin:10px;" class="icon-folder-upload3" />
    <i style="font-size:32px;margin:10px;" class="icon-folder5" />
    <i style="font-size:32px;margin:10px;" class="icon-folder-open2" />
    <i style="font-size:32px;margin:10px;" class="icon-folder6" />
    <i style="font-size:32px;margin:10px;" class="icon-folder-open3" />
    <i style="font-size:32px;margin:10px;" class="icon-certificate" />
    <i style="font-size:32px;margin:10px;" class="icon-cc" />
    <i style="font-size:32px;margin:10px;" class="icon-price-tag" />
    <i style="font-size:32px;margin:10px;" class="icon-price-tag2" />
    <i style="font-size:32px;margin:10px;" class="icon-price-tags" />
    <i style="font-size:32px;margin:10px;" class="icon-price-tag3" />
    <i style="font-size:32px;margin:10px;" class="icon-price-tags2" />
    <i style="font-size:32px;margin:10px;" class="icon-barcode2" />
    <i style="font-size:32px;margin:10px;" class="icon-qrcode" />
    <i style="font-size:32px;margin:10px;" class="icon-ticket" />
    <i style="font-size:32px;margin:10px;" class="icon-theater" />
    <i style="font-size:32px;margin:10px;" class="icon-store" />
    <i style="font-size:32px;margin:10px;" class="icon-store2" />
    <i style="font-size:32px;margin:10px;" class="icon-cart" />
    <i style="font-size:32px;margin:10px;" class="icon-cart2" />
    <i style="font-size:32px;margin:10px;" class="icon-cart4" />
    <i style="font-size:32px;margin:10px;" class="icon-cart5" />
    <i style="font-size:32px;margin:10px;" class="icon-cart-add" />
    <i style="font-size:32px;margin:10px;" class="icon-cart-add2" />
    <i style="font-size:32px;margin:10px;" class="icon-cart-remove" />
    <i style="font-size:32px;margin:10px;" class="icon-basket" />
    <i style="font-size:32px;margin:10px;" class="icon-bag" />
    <i style="font-size:32px;margin:10px;" class="icon-percent" />
    <i style="font-size:32px;margin:10px;" class="icon-coins" />
    <i style="font-size:32px;margin:10px;" class="icon-coin-dollar" />
    <i style="font-size:32px;margin:10px;" class="icon-coin-euro" />
    <i style="font-size:32px;margin:10px;" class="icon-coin-pound" />
    <i style="font-size:32px;margin:10px;" class="icon-coin-yen" />
    <i style="font-size:32px;margin:10px;" class="icon-piggy-bank" />
    <i style="font-size:32px;margin:10px;" class="icon-wallet" />
    <i style="font-size:32px;margin:10px;" class="icon-cash" />
    <i style="font-size:32px;margin:10px;" class="icon-cash2" />
    <i style="font-size:32px;margin:10px;" class="icon-cash3" />
    <i style="font-size:32px;margin:10px;" class="icon-cash4" />
    <i style="font-size:32px;margin:10px;" class="icon-credit-card" />
    <i style="font-size:32px;margin:10px;" class="icon-credit-card2" />
    <i style="font-size:32px;margin:10px;" class="icon-calculator4" />
    <i style="font-size:32px;margin:10px;" class="icon-calculator2" />
    <i style="font-size:32px;margin:10px;" class="icon-calculator3" />
    <i style="font-size:32px;margin:10px;" class="icon-chip" />
    <i style="font-size:32px;margin:10px;" class="icon-lifebuoy" />
    <i style="font-size:32px;margin:10px;" class="icon-phone" />
    <i style="font-size:32px;margin:10px;" class="icon-phone2" />
    <i style="font-size:32px;margin:10px;" class="icon-phone-slash" />
    <i style="font-size:32px;margin:10px;" class="icon-phone-wave" />
    <i style="font-size:32px;margin:10px;" class="icon-phone-plus" />
    <i style="font-size:32px;margin:10px;" class="icon-phone-minus" />
    <i style="font-size:32px;margin:10px;" class="icon-phone-plus2" />
    <i style="font-size:32px;margin:10px;" class="icon-phone-minus2" />
    <i style="font-size:32px;margin:10px;" class="icon-phone-incoming" />
    <i style="font-size:32px;margin:10px;" class="icon-phone-outgoing" />
    <i style="font-size:32px;margin:10px;" class="icon-phone-hang-up" />
    <i style="font-size:32px;margin:10px;" class="icon-address-book" />
    <i style="font-size:32px;margin:10px;" class="icon-address-book2" />
    <i style="font-size:32px;margin:10px;" class="icon-address-book3" />
    <i style="font-size:32px;margin:10px;" class="icon-notebook" />
    <i style="font-size:32px;margin:10px;" class="icon-envelop" />
    <i style="font-size:32px;margin:10px;" class="icon-envelop2" />
    <i style="font-size:32px;margin:10px;" class="icon-envelop3" />
    <i style="font-size:32px;margin:10px;" class="icon-envelop4" />
    <i style="font-size:32px;margin:10px;" class="icon-envelop5" />
    <i style="font-size:32px;margin:10px;" class="icon-mailbox" />
    <i style="font-size:32px;margin:10px;" class="icon-pushpin" />
    <i style="font-size:32px;margin:10px;" class="icon-location3" />
    <i style="font-size:32px;margin:10px;" class="icon-location4" />
    <i style="font-size:32px;margin:10px;" class="icon-compass4" />
    <i style="font-size:32px;margin:10px;" class="icon-map" />
    <i style="font-size:32px;margin:10px;" class="icon-map4" />
    <i style="font-size:32px;margin:10px;" class="icon-map5" />
    <i style="font-size:32px;margin:10px;" class="icon-direction" />
    <i style="font-size:32px;margin:10px;" class="icon-reset" />
    <i style="font-size:32px;margin:10px;" class="icon-history" />
    <i style="font-size:32px;margin:10px;" class="icon-watch" />
    <i style="font-size:32px;margin:10px;" class="icon-watch2" />
    <i style="font-size:32px;margin:10px;" class="icon-alarm" />
    <i style="font-size:32px;margin:10px;" class="icon-alarm-add" />
    <i style="font-size:32px;margin:10px;" class="icon-alarm-check" />
    <i style="font-size:32px;margin:10px;" class="icon-alarm-cancel" />
    <i style="font-size:32px;margin:10px;" class="icon-bell2" />
    <i style="font-size:32px;margin:10px;" class="icon-bell3" />
    <i style="font-size:32px;margin:10px;" class="icon-bell-plus" />
    <i style="font-size:32px;margin:10px;" class="icon-bell-minus" />
    <i style="font-size:32px;margin:10px;" class="icon-bell-check" />
    <i style="font-size:32px;margin:10px;" class="icon-bell-cross" />
    <i style="font-size:32px;margin:10px;" class="icon-calendar" />
    <i style="font-size:32px;margin:10px;" class="icon-calendar2" />
    <i style="font-size:32px;margin:10px;" class="icon-calendar3" />
    <i style="font-size:32px;margin:10px;" class="icon-calendar52" />
    <i style="font-size:32px;margin:10px;" class="icon-printer" />
    <i style="font-size:32px;margin:10px;" class="icon-printer2" />
    <i style="font-size:32px;margin:10px;" class="icon-printer4" />
    <i style="font-size:32px;margin:10px;" class="icon-shredder" />
    <i style="font-size:32px;margin:10px;" class="icon-mouse" />
    <i style="font-size:32px;margin:10px;" class="icon-mouse-left" />
    <i style="font-size:32px;margin:10px;" class="icon-mouse-right" />
    <i style="font-size:32px;margin:10px;" class="icon-keyboard" />
    <i style="font-size:32px;margin:10px;" class="icon-typewriter" />
    <i style="font-size:32px;margin:10px;" class="icon-display" />
    <i style="font-size:32px;margin:10px;" class="icon-display4" />
    <i style="font-size:32px;margin:10px;" class="icon-laptop" />
    <i style="font-size:32px;margin:10px;" class="icon-mobile" />
    <i style="font-size:32px;margin:10px;" class="icon-mobile2" />
    <i style="font-size:32px;margin:10px;" class="icon-tablet" />
    <i style="font-size:32px;margin:10px;" class="icon-mobile3" />
    <i style="font-size:32px;margin:10px;" class="icon-tv" />
    <i style="font-size:32px;margin:10px;" class="icon-radio" />
    <i style="font-size:32px;margin:10px;" class="icon-cabinet" />
    <i style="font-size:32px;margin:10px;" class="icon-drawer" />
    <i style="font-size:32px;margin:10px;" class="icon-drawer2" />
    <i style="font-size:32px;margin:10px;" class="icon-drawer-out" />
    <i style="font-size:32px;margin:10px;" class="icon-drawer-in" />
    <i style="font-size:32px;margin:10px;" class="icon-drawer3" />
    <i style="font-size:32px;margin:10px;" class="icon-box" />
    <i style="font-size:32px;margin:10px;" class="icon-box-add" />
    <i style="font-size:32px;margin:10px;" class="icon-box-remove" />
    <i style="font-size:32px;margin:10px;" class="icon-download" />
    <i style="font-size:32px;margin:10px;" class="icon-upload" />
    <i style="font-size:32px;margin:10px;" class="icon-floppy-disk" />
    <i style="font-size:32px;margin:10px;" class="icon-floppy-disks" />
    <i style="font-size:32px;margin:10px;" class="icon-usb-stick" />
    <i style="font-size:32px;margin:10px;" class="icon-drive" />
    <i style="font-size:32px;margin:10px;" class="icon-server" />
    <i style="font-size:32px;margin:10px;" class="icon-database" />
    <i style="font-size:32px;margin:10px;" class="icon-database2" />
    <i style="font-size:32px;margin:10px;" class="icon-database4" />
    <i style="font-size:32px;margin:10px;" class="icon-database-menu" />
    <i style="font-size:32px;margin:10px;" class="icon-database-add" />
    <i style="font-size:32px;margin:10px;" class="icon-database-remove" />
    <i style="font-size:32px;margin:10px;" class="icon-database-insert" />
    <i style="font-size:32px;margin:10px;" class="icon-database-export" />
    <i style="font-size:32px;margin:10px;" class="icon-database-upload" />
    <i style="font-size:32px;margin:10px;" class="icon-database-refresh" />
    <i style="font-size:32px;margin:10px;" class="icon-database-diff" />
    <i style="font-size:32px;margin:10px;" class="icon-database-edit2" />
    <i style="font-size:32px;margin:10px;" class="icon-database-check" />
    <i style="font-size:32px;margin:10px;" class="icon-database-arrow" />
    <i style="font-size:32px;margin:10px;" class="icon-database-time2" />
    <i style="font-size:32px;margin:10px;" class="icon-undo" />
    <i style="font-size:32px;margin:10px;" class="icon-redo" />
    <i style="font-size:32px;margin:10px;" class="icon-rotate-ccw" />
    <i style="font-size:32px;margin:10px;" class="icon-rotate-cw" />
    <i style="font-size:32px;margin:10px;" class="icon-rotate-ccw2" />
    <i style="font-size:32px;margin:10px;" class="icon-rotate-cw2" />
    <i style="font-size:32px;margin:10px;" class="icon-rotate-ccw3" />
    <i style="font-size:32px;margin:10px;" class="icon-rotate-cw3" />
    <i style="font-size:32px;margin:10px;" class="icon-flip-vertical2" />
    <i style="font-size:32px;margin:10px;" class="icon-flip-horizontal2" />
    <i style="font-size:32px;margin:10px;" class="icon-flip-vertical3" />
    <i style="font-size:32px;margin:10px;" class="icon-flip-vertical4" />
    <i style="font-size:32px;margin:10px;" class="icon-angle" />
    <i style="font-size:32px;margin:10px;" class="icon-shear" />
    <i style="font-size:32px;margin:10px;" class="icon-align-left" />
    <i style="font-size:32px;margin:10px;" class="icon-align-center-horizontal" />
    <i style="font-size:32px;margin:10px;" class="icon-align-right" />
    <i style="font-size:32px;margin:10px;" class="icon-align-top" />
    <i style="font-size:32px;margin:10px;" class="icon-align-center-vertical" />
    <i style="font-size:32px;margin:10px;" class="icon-align-bottom" />
    <i style="font-size:32px;margin:10px;" class="icon-undo2" />
    <i style="font-size:32px;margin:10px;" class="icon-redo2" />
    <i style="font-size:32px;margin:10px;" class="icon-forward" />
    <i style="font-size:32px;margin:10px;" class="icon-reply" />
    <i style="font-size:32px;margin:10px;" class="icon-reply-all" />
    <i style="font-size:32px;margin:10px;" class="icon-bubble" />
    <i style="font-size:32px;margin:10px;" class="icon-bubbles" />
    <i style="font-size:32px;margin:10px;" class="icon-bubbles2" />
    <i style="font-size:32px;margin:10px;" class="icon-bubble2" />
    <i style="font-size:32px;margin:10px;" class="icon-bubbles3" />
    <i style="font-size:32px;margin:10px;" class="icon-bubbles4" />
    <i style="font-size:32px;margin:10px;" class="icon-bubble-notification" />
    <i style="font-size:32px;margin:10px;" class="icon-bubbles5" />
    <i style="font-size:32px;margin:10px;" class="icon-bubbles6" />
    <i style="font-size:32px;margin:10px;" class="icon-bubble6" />
    <i style="font-size:32px;margin:10px;" class="icon-bubbles7" />
    <i style="font-size:32px;margin:10px;" class="icon-bubble7" />
    <i style="font-size:32px;margin:10px;" class="icon-bubbles8" />
    <i style="font-size:32px;margin:10px;" class="icon-bubble8" />
    <i style="font-size:32px;margin:10px;" class="icon-bubble-dots3" />
    <i style="font-size:32px;margin:10px;" class="icon-bubble-lines3" />
    <i style="font-size:32px;margin:10px;" class="icon-bubble9" />
    <i style="font-size:32px;margin:10px;" class="icon-bubble-dots4" />
    <i style="font-size:32px;margin:10px;" class="icon-bubble-lines4" />
    <i style="font-size:32px;margin:10px;" class="icon-bubbles9" />
    <i style="font-size:32px;margin:10px;" class="icon-bubbles10" />
    <i style="font-size:32px;margin:10px;" class="icon-user" />
    <i style="font-size:32px;margin:10px;" class="icon-users" />
    <i style="font-size:32px;margin:10px;" class="icon-user-plus" />
    <i style="font-size:32px;margin:10px;" class="icon-user-minus" />
    <i style="font-size:32px;margin:10px;" class="icon-user-cancel" />
    <i style="font-size:32px;margin:10px;" class="icon-user-block" />
    <i style="font-size:32px;margin:10px;" class="icon-user-lock" />
    <i style="font-size:32px;margin:10px;" class="icon-user-check" />
    <i style="font-size:32px;margin:10px;" class="icon-users2" />
    <i style="font-size:32px;margin:10px;" class="icon-users4" />
    <i style="font-size:32px;margin:10px;" class="icon-user-tie" />
    <i style="font-size:32px;margin:10px;" class="icon-collaboration" />
    <i style="font-size:32px;margin:10px;" class="icon-vcard" />
    <i style="font-size:32px;margin:10px;" class="icon-hat" />
    <i style="font-size:32px;margin:10px;" class="icon-bowtie" />
    <i style="font-size:32px;margin:10px;" class="icon-quotes-left" />
    <i style="font-size:32px;margin:10px;" class="icon-quotes-right" />
    <i style="font-size:32px;margin:10px;" class="icon-quotes-left2" />
    <i style="font-size:32px;margin:10px;" class="icon-quotes-right2" />
    <i style="font-size:32px;margin:10px;" class="icon-hour-glass" />
    <i style="font-size:32px;margin:10px;" class="icon-hour-glass2" />
    <i style="font-size:32px;margin:10px;" class="icon-hour-glass3" />
    <i style="font-size:32px;margin:10px;" class="icon-spinner" />
    <i style="font-size:32px;margin:10px;" class="icon-spinner2" />
    <i style="font-size:32px;margin:10px;" class="icon-spinner3" />
    <i style="font-size:32px;margin:10px;" class="icon-spinner4" />
    <i style="font-size:32px;margin:10px;" class="icon-spinner6" />
    <i style="font-size:32px;margin:10px;" class="icon-spinner9" />
    <i style="font-size:32px;margin:10px;" class="icon-spinner10" />
    <i style="font-size:32px;margin:10px;" class="icon-spinner11" />
    <i style="font-size:32px;margin:10px;" class="icon-microscope" />
    <i style="font-size:32px;margin:10px;" class="icon-enlarge" />
    <i style="font-size:32px;margin:10px;" class="icon-shrink" />
    <i style="font-size:32px;margin:10px;" class="icon-enlarge3" />
    <i style="font-size:32px;margin:10px;" class="icon-shrink3" />
    <i style="font-size:32px;margin:10px;" class="icon-enlarge5" />
    <i style="font-size:32px;margin:10px;" class="icon-shrink5" />
    <i style="font-size:32px;margin:10px;" class="icon-enlarge6" />
    <i style="font-size:32px;margin:10px;" class="icon-shrink6" />
    <i style="font-size:32px;margin:10px;" class="icon-enlarge7" />
    <i style="font-size:32px;margin:10px;" class="icon-shrink7" />
    <i style="font-size:32px;margin:10px;" class="icon-key" />
    <i style="font-size:32px;margin:10px;" class="icon-lock" />
    <i style="font-size:32px;margin:10px;" class="icon-lock2" />
    <i style="font-size:32px;margin:10px;" class="icon-lock4" />
    <i style="font-size:32px;margin:10px;" class="icon-unlocked" />
    <i style="font-size:32px;margin:10px;" class="icon-lock5" />
    <i style="font-size:32px;margin:10px;" class="icon-unlocked2" />
    <i style="font-size:32px;margin:10px;" class="icon-safe" />
    <i style="font-size:32px;margin:10px;" class="icon-wrench" />
    <i style="font-size:32px;margin:10px;" class="icon-wrench2" />
    <i style="font-size:32px;margin:10px;" class="icon-wrench3" />
    <i style="font-size:32px;margin:10px;" class="icon-equalizer" />
    <i style="font-size:32px;margin:10px;" class="icon-equalizer2" />
    <i style="font-size:32px;margin:10px;" class="icon-equalizer3" />
    <i style="font-size:32px;margin:10px;" class="icon-equalizer4" />
    <i style="font-size:32px;margin:10px;" class="icon-cog" />
    <i style="font-size:32px;margin:10px;" class="icon-cogs" />
    <i style="font-size:32px;margin:10px;" class="icon-cog2" />
    <i style="font-size:32px;margin:10px;" class="icon-cog3" />
    <i style="font-size:32px;margin:10px;" class="icon-cog4" />
    <i style="font-size:32px;margin:10px;" class="icon-cog52" />
    <i style="font-size:32px;margin:10px;" class="icon-cog6" />
    <i style="font-size:32px;margin:10px;" class="icon-cog7" />
    <i style="font-size:32px;margin:10px;" class="icon-hammer" />
    <i style="font-size:32px;margin:10px;" class="icon-hammer-wrench" />
    <i style="font-size:32px;margin:10px;" class="icon-magic-wand" />
    <i style="font-size:32px;margin:10px;" class="icon-magic-wand2" />
    <i style="font-size:32px;margin:10px;" class="icon-pulse2" />
    <i style="font-size:32px;margin:10px;" class="icon-aid-kit" />
    <i style="font-size:32px;margin:10px;" class="icon-bug2" />
    <i style="font-size:32px;margin:10px;" class="icon-construction" />
    <i style="font-size:32px;margin:10px;" class="icon-traffic-cone" />
    <i style="font-size:32px;margin:10px;" class="icon-traffic-lights" />
    <i style="font-size:32px;margin:10px;" class="icon-pie-chart" />
    <i style="font-size:32px;margin:10px;" class="icon-pie-chart2" />
    <i style="font-size:32px;margin:10px;" class="icon-pie-chart3" />
    <i style="font-size:32px;margin:10px;" class="icon-pie-chart4" />
    <i style="font-size:32px;margin:10px;" class="icon-pie-chart5" />
    <i style="font-size:32px;margin:10px;" class="icon-pie-chart6" />
    <i style="font-size:32px;margin:10px;" class="icon-pie-chart7" />
    <i style="font-size:32px;margin:10px;" class="icon-stats-dots" />
    <i style="font-size:32px;margin:10px;" class="icon-stats-bars" />
    <i style="font-size:32px;margin:10px;" class="icon-pie-chart8" />
    <i style="font-size:32px;margin:10px;" class="icon-stats-bars2" />
    <i style="font-size:32px;margin:10px;" class="icon-stats-bars3" />
    <i style="font-size:32px;margin:10px;" class="icon-stats-bars4" />
    <i style="font-size:32px;margin:10px;" class="icon-chart" />
    <i style="font-size:32px;margin:10px;" class="icon-stats-growth" />
    <i style="font-size:32px;margin:10px;" class="icon-stats-decline" />
    <i style="font-size:32px;margin:10px;" class="icon-stats-growth2" />
    <i style="font-size:32px;margin:10px;" class="icon-stats-decline2" />
    <i style="font-size:32px;margin:10px;" class="icon-stairs-up" />
    <i style="font-size:32px;margin:10px;" class="icon-stairs-down" />
    <i style="font-size:32px;margin:10px;" class="icon-stairs" />
    <i style="font-size:32px;margin:10px;" class="icon-ladder" />
    <i style="font-size:32px;margin:10px;" class="icon-rating" />
    <i style="font-size:32px;margin:10px;" class="icon-rating2" />
    <i style="font-size:32px;margin:10px;" class="icon-rating3" />
    <i style="font-size:32px;margin:10px;" class="icon-podium" />
    <i style="font-size:32px;margin:10px;" class="icon-stars" />
    <i style="font-size:32px;margin:10px;" class="icon-medal-star" />
    <i style="font-size:32px;margin:10px;" class="icon-medal" />
    <i style="font-size:32px;margin:10px;" class="icon-medal2" />
    <i style="font-size:32px;margin:10px;" class="icon-medal-first" />
    <i style="font-size:32px;margin:10px;" class="icon-medal-second" />
    <i style="font-size:32px;margin:10px;" class="icon-medal-third" />
    <i style="font-size:32px;margin:10px;" class="icon-crown" />
    <i style="font-size:32px;margin:10px;" class="icon-trophy2" />
    <i style="font-size:32px;margin:10px;" class="icon-trophy3" />
    <i style="font-size:32px;margin:10px;" class="icon-diamond" />
    <i style="font-size:32px;margin:10px;" class="icon-trophy4" />
    <i style="font-size:32px;margin:10px;" class="icon-gift" />
    <i style="font-size:32px;margin:10px;" class="icon-pipe" />
    <i style="font-size:32px;margin:10px;" class="icon-mustache" />
    <i style="font-size:32px;margin:10px;" class="icon-cup2" />
    <i style="font-size:32px;margin:10px;" class="icon-coffee" />
    <i style="font-size:32px;margin:10px;" class="icon-paw" />
    <i style="font-size:32px;margin:10px;" class="icon-footprint" />
    <i style="font-size:32px;margin:10px;" class="icon-rocket" />
    <i style="font-size:32px;margin:10px;" class="icon-meter2" />
    <i style="font-size:32px;margin:10px;" class="icon-meter-slow" />
    <i style="font-size:32px;margin:10px;" class="icon-meter-fast" />
    <i style="font-size:32px;margin:10px;" class="icon-hammer2" />
    <i style="font-size:32px;margin:10px;" class="icon-balance" />
    <i style="font-size:32px;margin:10px;" class="icon-fire" />
    <i style="font-size:32px;margin:10px;" class="icon-fire2" />
    <i style="font-size:32px;margin:10px;" class="icon-lab" />
    <i style="font-size:32px;margin:10px;" class="icon-atom" />
    <i style="font-size:32px;margin:10px;" class="icon-atom2" />
    <i style="font-size:32px;margin:10px;" class="icon-bin" />
    <i style="font-size:32px;margin:10px;" class="icon-bin2" />
    <i style="font-size:32px;margin:10px;" class="icon-briefcase" />
    <i style="font-size:32px;margin:10px;" class="icon-briefcase3" />
    <i style="font-size:32px;margin:10px;" class="icon-airplane2" />
    <i style="font-size:32px;margin:10px;" class="icon-airplane3" />
    <i style="font-size:32px;margin:10px;" class="icon-airplane4" />
    <i style="font-size:32px;margin:10px;" class="icon-paperplane" />
    <i style="font-size:32px;margin:10px;" class="icon-car" />
    <i style="font-size:32px;margin:10px;" class="icon-steering-wheel" />
    <i style="font-size:32px;margin:10px;" class="icon-car2" />
    <i style="font-size:32px;margin:10px;" class="icon-gas" />
    <i style="font-size:32px;margin:10px;" class="icon-bus" />
    <i style="font-size:32px;margin:10px;" class="icon-truck" />
    <i style="font-size:32px;margin:10px;" class="icon-bike" />
    <i style="font-size:32px;margin:10px;" class="icon-road" />
    <i style="font-size:32px;margin:10px;" class="icon-train" />
    <i style="font-size:32px;margin:10px;" class="icon-train2" />
    <i style="font-size:32px;margin:10px;" class="icon-ship" />
    <i style="font-size:32px;margin:10px;" class="icon-boat" />
    <i style="font-size:32px;margin:10px;" class="icon-chopper" />
    <i style="font-size:32px;margin:10px;" class="icon-cube" />
    <i style="font-size:32px;margin:10px;" class="icon-cube2" />
    <i style="font-size:32px;margin:10px;" class="icon-cube3" />
    <i style="font-size:32px;margin:10px;" class="icon-cube4" />
    <i style="font-size:32px;margin:10px;" class="icon-pyramid" />
    <i style="font-size:32px;margin:10px;" class="icon-pyramid2" />
    <i style="font-size:32px;margin:10px;" class="icon-package" />
    <i style="font-size:32px;margin:10px;" class="icon-puzzle" />
    <i style="font-size:32px;margin:10px;" class="icon-puzzle2" />
    <i style="font-size:32px;margin:10px;" class="icon-puzzle3" />
    <i style="font-size:32px;margin:10px;" class="icon-puzzle4" />
    <i style="font-size:32px;margin:10px;" class="icon-glasses-3d2" />
    <i style="font-size:32px;margin:10px;" class="icon-brain" />
    <i style="font-size:32px;margin:10px;" class="icon-accessibility" />
    <i style="font-size:32px;margin:10px;" class="icon-accessibility2" />
    <i style="font-size:32px;margin:10px;" class="icon-strategy" />
    <i style="font-size:32px;margin:10px;" class="icon-target" />
    <i style="font-size:32px;margin:10px;" class="icon-target2" />
    <i style="font-size:32px;margin:10px;" class="icon-shield-check" />
    <i style="font-size:32px;margin:10px;" class="icon-shield-notice" />
    <i style="font-size:32px;margin:10px;" class="icon-shield2" />
    <i style="font-size:32px;margin:10px;" class="icon-racing" />
    <i style="font-size:32px;margin:10px;" class="icon-finish" />
    <i style="font-size:32px;margin:10px;" class="icon-power2" />
    <i style="font-size:32px;margin:10px;" class="icon-power3" />
    <i style="font-size:32px;margin:10px;" class="icon-switch" />
    <i style="font-size:32px;margin:10px;" class="icon-switch22" />
    <i style="font-size:32px;margin:10px;" class="icon-power-cord" />
    <i style="font-size:32px;margin:10px;" class="icon-clipboard" />
    <i style="font-size:32px;margin:10px;" class="icon-clipboard2" />
    <i style="font-size:32px;margin:10px;" class="icon-clipboard3" />
    <i style="font-size:32px;margin:10px;" class="icon-clipboard4" />
    <i style="font-size:32px;margin:10px;" class="icon-clipboard5" />
    <i style="font-size:32px;margin:10px;" class="icon-clipboard6" />
    <i style="font-size:32px;margin:10px;" class="icon-playlist" />
    <i style="font-size:32px;margin:10px;" class="icon-playlist-add" />
    <i style="font-size:32px;margin:10px;" class="icon-list-numbered" />
    <i style="font-size:32px;margin:10px;" class="icon-list" />
    <i style="font-size:32px;margin:10px;" class="icon-list2" />
    <i style="font-size:32px;margin:10px;" class="icon-more" />
    <i style="font-size:32px;margin:10px;" class="icon-more2" />
    <i style="font-size:32px;margin:10px;" class="icon-grid" />
    <i style="font-size:32px;margin:10px;" class="icon-grid2" />
    <i style="font-size:32px;margin:10px;" class="icon-grid3" />
    <i style="font-size:32px;margin:10px;" class="icon-grid4" />
    <i style="font-size:32px;margin:10px;" class="icon-grid52" />
    <i style="font-size:32px;margin:10px;" class="icon-grid6" />
    <i style="font-size:32px;margin:10px;" class="icon-grid7" />
    <i style="font-size:32px;margin:10px;" class="icon-tree5" />
    <i style="font-size:32px;margin:10px;" class="icon-tree6" />
    <i style="font-size:32px;margin:10px;" class="icon-tree7" />
    <i style="font-size:32px;margin:10px;" class="icon-lan" />
    <i style="font-size:32px;margin:10px;" class="icon-lan2" />
    <i style="font-size:32px;margin:10px;" class="icon-lan3" />
    <i style="font-size:32px;margin:10px;" class="icon-menu" />
    <i style="font-size:32px;margin:10px;" class="icon-circle-small" />
    <i style="font-size:32px;margin:10px;" class="icon-menu2" />
    <i style="font-size:32px;margin:10px;" class="icon-menu3" />
    <i style="font-size:32px;margin:10px;" class="icon-menu4" />
    <i style="font-size:32px;margin:10px;" class="icon-menu5" />
    <i style="font-size:32px;margin:10px;" class="icon-menu62" />
    <i style="font-size:32px;margin:10px;" class="icon-menu7" />
    <i style="font-size:32px;margin:10px;" class="icon-menu8" />
    <i style="font-size:32px;margin:10px;" class="icon-menu9" />
    <i style="font-size:32px;margin:10px;" class="icon-menu10" />
    <i style="font-size:32px;margin:10px;" class="icon-cloud" />
    <i style="font-size:32px;margin:10px;" class="icon-cloud-download" />
    <i style="font-size:32px;margin:10px;" class="icon-cloud-upload" />
    <i style="font-size:32px;margin:10px;" class="icon-cloud-check" />
    <i style="font-size:32px;margin:10px;" class="icon-cloud2" />
    <i style="font-size:32px;margin:10px;" class="icon-cloud-download2" />
    <i style="font-size:32px;margin:10px;" class="icon-cloud-upload2" />
    <i style="font-size:32px;margin:10px;" class="icon-cloud-check2" />
    <i style="font-size:32px;margin:10px;" class="icon-import" />
    <i style="font-size:32px;margin:10px;" class="icon-download4" />
    <i style="font-size:32px;margin:10px;" class="icon-upload4" />
    <i style="font-size:32px;margin:10px;" class="icon-download7" />
    <i style="font-size:32px;margin:10px;" class="icon-upload7" />
    <i style="font-size:32px;margin:10px;" class="icon-download10" />
    <i style="font-size:32px;margin:10px;" class="icon-upload10" />
    <i style="font-size:32px;margin:10px;" class="icon-sphere" />
    <i style="font-size:32px;margin:10px;" class="icon-sphere3" />
    <i style="font-size:32px;margin:10px;" class="icon-earth" />
    <i style="font-size:32px;margin:10px;" class="icon-link" />
    <i style="font-size:32px;margin:10px;" class="icon-unlink" />
    <i style="font-size:32px;margin:10px;" class="icon-link2" />
    <i style="font-size:32px;margin:10px;" class="icon-unlink2" />
    <i style="font-size:32px;margin:10px;" class="icon-anchor" />
    <i style="font-size:32px;margin:10px;" class="icon-flag3" />
    <i style="font-size:32px;margin:10px;" class="icon-flag4" />
    <i style="font-size:32px;margin:10px;" class="icon-flag7" />
    <i style="font-size:32px;margin:10px;" class="icon-flag8" />
    <i style="font-size:32px;margin:10px;" class="icon-attachment" />
    <i style="font-size:32px;margin:10px;" class="icon-attachment2" />
    <i style="font-size:32px;margin:10px;" class="icon-eye" />
    <i style="font-size:32px;margin:10px;" class="icon-eye-plus" />
    <i style="font-size:32px;margin:10px;" class="icon-eye-minus" />
    <i style="font-size:32px;margin:10px;" class="icon-eye-blocked" />
    <i style="font-size:32px;margin:10px;" class="icon-eye2" />
    <i style="font-size:32px;margin:10px;" class="icon-eye-blocked2" />
    <i style="font-size:32px;margin:10px;" class="icon-eye4" />
    <i style="font-size:32px;margin:10px;" class="icon-bookmark2" />
    <i style="font-size:32px;margin:10px;" class="icon-bookmark3" />
    <i style="font-size:32px;margin:10px;" class="icon-bookmarks" />
    <i style="font-size:32px;margin:10px;" class="icon-bookmark4" />
    <i style="font-size:32px;margin:10px;" class="icon-spotlight2" />
    <i style="font-size:32px;margin:10px;" class="icon-starburst" />
    <i style="font-size:32px;margin:10px;" class="icon-snowflake" />
    <i style="font-size:32px;margin:10px;" class="icon-weather-windy" />
    <i style="font-size:32px;margin:10px;" class="icon-fan" />
    <i style="font-size:32px;margin:10px;" class="icon-umbrella" />
    <i style="font-size:32px;margin:10px;" class="icon-sun3" />
    <i style="font-size:32px;margin:10px;" class="icon-contrast" />
    <i style="font-size:32px;margin:10px;" class="icon-bed2" />
    <i style="font-size:32px;margin:10px;" class="icon-furniture" />
    <i style="font-size:32px;margin:10px;" class="icon-chair" />
    <i style="font-size:32px;margin:10px;" class="icon-star-empty3" />
    <i style="font-size:32px;margin:10px;" class="icon-star-half" />
    <i style="font-size:32px;margin:10px;" class="icon-star-full2" />
    <i style="font-size:32px;margin:10px;" class="icon-heart5" />
    <i style="font-size:32px;margin:10px;" class="icon-heart6" />
    <i style="font-size:32px;margin:10px;" class="icon-heart-broken2" />
    <i style="font-size:32px;margin:10px;" class="icon-thumbs-up2" />
    <i style="font-size:32px;margin:10px;" class="icon-thumbs-down2" />
    <i style="font-size:32px;margin:10px;" class="icon-thumbs-up3" />
    <i style="font-size:32px;margin:10px;" class="icon-thumbs-down3" />
    <i style="font-size:32px;margin:10px;" class="icon-height" />
    <i style="font-size:32px;margin:10px;" class="icon-man" />
    <i style="font-size:32px;margin:10px;" class="icon-woman" />
    <i style="font-size:32px;margin:10px;" class="icon-man-woman" />
    <i style="font-size:32px;margin:10px;" class="icon-yin-yang" />
    <i style="font-size:32px;margin:10px;" class="icon-cursor" />
    <i style="font-size:32px;margin:10px;" class="icon-cursor2" />
    <i style="font-size:32px;margin:10px;" class="icon-lasso2" />
    <i style="font-size:32px;margin:10px;" class="icon-select2" />
    <i style="font-size:32px;margin:10px;" class="icon-point-up" />
    <i style="font-size:32px;margin:10px;" class="icon-point-right" />
    <i style="font-size:32px;margin:10px;" class="icon-point-down" />
    <i style="font-size:32px;margin:10px;" class="icon-point-left" />
    <i style="font-size:32px;margin:10px;" class="icon-pointer" />
    <i style="font-size:32px;margin:10px;" class="icon-reminder" />
    <i style="font-size:32px;margin:10px;" class="icon-drag-left-right" />
    <i style="font-size:32px;margin:10px;" class="icon-drag-left" />
    <i style="font-size:32px;margin:10px;" class="icon-drag-right" />
    <i style="font-size:32px;margin:10px;" class="icon-touch" />
    <i style="font-size:32px;margin:10px;" class="icon-multitouch" />
    <i style="font-size:32px;margin:10px;" class="icon-touch-zoom" />
    <i style="font-size:32px;margin:10px;" class="icon-touch-pinch" />
    <i style="font-size:32px;margin:10px;" class="icon-hand" />
    <i style="font-size:32px;margin:10px;" class="icon-grab" />
    <i style="font-size:32px;margin:10px;" class="icon-stack-empty" />
    <i style="font-size:32px;margin:10px;" class="icon-stack-plus" />
    <i style="font-size:32px;margin:10px;" class="icon-stack-minus" />
    <i style="font-size:32px;margin:10px;" class="icon-stack-star" />
    <i style="font-size:32px;margin:10px;" class="icon-stack-picture" />
    <i style="font-size:32px;margin:10px;" class="icon-stack-down" />
    <i style="font-size:32px;margin:10px;" class="icon-stack-up" />
    <i style="font-size:32px;margin:10px;" class="icon-stack-cancel" />
    <i style="font-size:32px;margin:10px;" class="icon-stack-check" />
    <i style="font-size:32px;margin:10px;" class="icon-stack-text" />
    <i style="font-size:32px;margin:10px;" class="icon-stack4" />
    <i style="font-size:32px;margin:10px;" class="icon-stack-music" />
    <i style="font-size:32px;margin:10px;" class="icon-stack-play" />
    <i style="font-size:32px;margin:10px;" class="icon-move" />
    <i style="font-size:32px;margin:10px;" class="icon-dots" />
    <i style="font-size:32px;margin:10px;" class="icon-warning" />
    <i style="font-size:32px;margin:10px;" class="icon-warning22" />
    <i style="font-size:32px;margin:10px;" class="icon-notification2" />
    <i style="font-size:32px;margin:10px;" class="icon-question3" />
    <i style="font-size:32px;margin:10px;" class="icon-question4" />
    <i style="font-size:32px;margin:10px;" class="icon-plus3" />
    <i style="font-size:32px;margin:10px;" class="icon-minus3" />
    <i style="font-size:32px;margin:10px;" class="icon-plus-circle2" />
    <i style="font-size:32px;margin:10px;" class="icon-minus-circle2" />
    <i style="font-size:32px;margin:10px;" class="icon-cancel-circle2" />
    <i style="font-size:32px;margin:10px;" class="icon-blocked" />
    <i style="font-size:32px;margin:10px;" class="icon-cancel-square" />
    <i style="font-size:32px;margin:10px;" class="icon-cancel-square2" />
    <i style="font-size:32px;margin:10px;" class="icon-spam" />
    <i style="font-size:32px;margin:10px;" class="icon-cross2" />
    <i style="font-size:32px;margin:10px;" class="icon-cross3" />
    <i style="font-size:32px;margin:10px;" class="icon-checkmark" />
    <i style="font-size:32px;margin:10px;" class="icon-checkmark3" />
    <i style="font-size:32px;margin:10px;" class="icon-checkmark2" />
    <i style="font-size:32px;margin:10px;" class="icon-checkmark4" />
    <i style="font-size:32px;margin:10px;" class="icon-spell-check" />
    <i style="font-size:32px;margin:10px;" class="icon-spell-check2" />
    <i style="font-size:32px;margin:10px;" class="icon-enter" />
    <i style="font-size:32px;margin:10px;" class="icon-exit" />
    <i style="font-size:32px;margin:10px;" class="icon-enter2" />
    <i style="font-size:32px;margin:10px;" class="icon-exit2" />
    <i style="font-size:32px;margin:10px;" class="icon-enter3" />
    <i style="font-size:32px;margin:10px;" class="icon-exit3" />
    <i style="font-size:32px;margin:10px;" class="icon-wall" />
    <i style="font-size:32px;margin:10px;" class="icon-fence" />
    <i style="font-size:32px;margin:10px;" class="icon-play3" />
    <i style="font-size:32px;margin:10px;" class="icon-pause" />
    <i style="font-size:32px;margin:10px;" class="icon-stop" />
    <i style="font-size:32px;margin:10px;" class="icon-previous" />
    <i style="font-size:32px;margin:10px;" class="icon-next" />
    <i style="font-size:32px;margin:10px;" class="icon-backward" />
    <i style="font-size:32px;margin:10px;" class="icon-forward2" />
    <i style="font-size:32px;margin:10px;" class="icon-play4" />
    <i style="font-size:32px;margin:10px;" class="icon-pause2" />
    <i style="font-size:32px;margin:10px;" class="icon-stop2" />
    <i style="font-size:32px;margin:10px;" class="icon-backward2" />
    <i style="font-size:32px;margin:10px;" class="icon-forward3" />
    <i style="font-size:32px;margin:10px;" class="icon-first" />
    <i style="font-size:32px;margin:10px;" class="icon-last" />
    <i style="font-size:32px;margin:10px;" class="icon-previous2" />
    <i style="font-size:32px;margin:10px;" class="icon-next2" />
    <i style="font-size:32px;margin:10px;" class="icon-eject" />
    <i style="font-size:32px;margin:10px;" class="icon-volume-high" />
    <i style="font-size:32px;margin:10px;" class="icon-volume-medium" />
    <i style="font-size:32px;margin:10px;" class="icon-volume-low" />
    <i style="font-size:32px;margin:10px;" class="icon-volume-mute" />
    <i style="font-size:32px;margin:10px;" class="icon-speaker-left" />
    <i style="font-size:32px;margin:10px;" class="icon-speaker-right" />
    <i style="font-size:32px;margin:10px;" class="icon-volume-mute2" />
    <i style="font-size:32px;margin:10px;" class="icon-volume-increase" />
    <i style="font-size:32px;margin:10px;" class="icon-volume-decrease" />
    <i style="font-size:32px;margin:10px;" class="icon-volume-mute5" />
    <i style="font-size:32px;margin:10px;" class="icon-loop" />
    <i style="font-size:32px;margin:10px;" class="icon-loop3" />
    <i style="font-size:32px;margin:10px;" class="icon-infinite-square" />
    <i style="font-size:32px;margin:10px;" class="icon-infinite" />
    <i style="font-size:32px;margin:10px;" class="icon-loop4" />
    <i style="font-size:32px;margin:10px;" class="icon-shuffle" />
    <i style="font-size:32px;margin:10px;" class="icon-wave" />
    <i style="font-size:32px;margin:10px;" class="icon-wave2" />
    <i style="font-size:32px;margin:10px;" class="icon-split" />
    <i style="font-size:32px;margin:10px;" class="icon-merge" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-up5" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-right5" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-down5" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-left5" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-up-left2" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-up7" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-up-right2" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-right7" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-down-right2" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-down7" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-down-left2" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-left7" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-up-left3" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-up8" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-up-right3" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-right8" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-down-right3" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-down8" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-down-left3" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-left8" />
    <i style="font-size:32px;margin:10px;" class="icon-circle-up2" />
    <i style="font-size:32px;margin:10px;" class="icon-circle-right2" />
    <i style="font-size:32px;margin:10px;" class="icon-circle-down2" />
    <i style="font-size:32px;margin:10px;" class="icon-circle-left2" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-resize7" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-resize8" />
    <i style="font-size:32px;margin:10px;" class="icon-square-up-left" />
    <i style="font-size:32px;margin:10px;" class="icon-square-up" />
    <i style="font-size:32px;margin:10px;" class="icon-square-up-right" />
    <i style="font-size:32px;margin:10px;" class="icon-square-right" />
    <i style="font-size:32px;margin:10px;" class="icon-square-down-right" />
    <i style="font-size:32px;margin:10px;" class="icon-square-down" />
    <i style="font-size:32px;margin:10px;" class="icon-square-down-left" />
    <i style="font-size:32px;margin:10px;" class="icon-square-left" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-up15" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-right15" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-down15" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-left15" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-up16" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-right16" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-down16" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-left16" />
    <i style="font-size:32px;margin:10px;" class="icon-menu-open" />
    <i style="font-size:32px;margin:10px;" class="icon-menu-open2" />
    <i style="font-size:32px;margin:10px;" class="icon-menu-close" />
    <i style="font-size:32px;margin:10px;" class="icon-menu-close2" />
    <i style="font-size:32px;margin:10px;" class="icon-enter5" />
    <i style="font-size:32px;margin:10px;" class="icon-esc" />
    <i style="font-size:32px;margin:10px;" class="icon-enter6" />
    <i style="font-size:32px;margin:10px;" class="icon-backspace" />
    <i style="font-size:32px;margin:10px;" class="icon-backspace2" />
    <i style="font-size:32px;margin:10px;" class="icon-tab" />
    <i style="font-size:32px;margin:10px;" class="icon-transmission" />
    <i style="font-size:32px;margin:10px;" class="icon-sort" />
    <i style="font-size:32px;margin:10px;" class="icon-move-up2" />
    <i style="font-size:32px;margin:10px;" class="icon-move-down2" />
    <i style="font-size:32px;margin:10px;" class="icon-sort-alpha-asc" />
    <i style="font-size:32px;margin:10px;" class="icon-sort-alpha-desc" />
    <i style="font-size:32px;margin:10px;" class="icon-sort-numeric-asc" />
    <i style="font-size:32px;margin:10px;" class="icon-sort-numberic-desc" />
    <i style="font-size:32px;margin:10px;" class="icon-sort-amount-asc" />
    <i style="font-size:32px;margin:10px;" class="icon-sort-amount-desc" />
    <i style="font-size:32px;margin:10px;" class="icon-sort-time-asc" />
    <i style="font-size:32px;margin:10px;" class="icon-sort-time-desc" />
    <i style="font-size:32px;margin:10px;" class="icon-battery-6" />
    <i style="font-size:32px;margin:10px;" class="icon-battery-0" />
    <i style="font-size:32px;margin:10px;" class="icon-battery-charging" />
    <i style="font-size:32px;margin:10px;" class="icon-command" />
    <i style="font-size:32px;margin:10px;" class="icon-shift" />
    <i style="font-size:32px;margin:10px;" class="icon-ctrl" />
    <i style="font-size:32px;margin:10px;" class="icon-opt" />
    <i style="font-size:32px;margin:10px;" class="icon-checkbox-checked" />
    <i style="font-size:32px;margin:10px;" class="icon-checkbox-unchecked" />
    <i style="font-size:32px;margin:10px;" class="icon-checkbox-partial" />
    <i style="font-size:32px;margin:10px;" class="icon-square" />
    <i style="font-size:32px;margin:10px;" class="icon-triangle" />
    <i style="font-size:32px;margin:10px;" class="icon-triangle2" />
    <i style="font-size:32px;margin:10px;" class="icon-diamond3" />
    <i style="font-size:32px;margin:10px;" class="icon-diamond4" />
    <i style="font-size:32px;margin:10px;" class="icon-checkbox-checked2" />
    <i style="font-size:32px;margin:10px;" class="icon-checkbox-unchecked2" />
    <i style="font-size:32px;margin:10px;" class="icon-checkbox-partial2" />
    <i style="font-size:32px;margin:10px;" class="icon-radio-checked" />
    <i style="font-size:32px;margin:10px;" class="icon-radio-checked2" />
    <i style="font-size:32px;margin:10px;" class="icon-radio-unchecked" />
    <i style="font-size:32px;margin:10px;" class="icon-checkmark-circle" />
    <i style="font-size:32px;margin:10px;" class="icon-circle" />
    <i style="font-size:32px;margin:10px;" class="icon-circle2" />
    <i style="font-size:32px;margin:10px;" class="icon-circles" />
    <i style="font-size:32px;margin:10px;" class="icon-circles2" />
    <i style="font-size:32px;margin:10px;" class="icon-crop" />
    <i style="font-size:32px;margin:10px;" class="icon-crop2" />
    <i style="font-size:32px;margin:10px;" class="icon-make-group" />
    <i style="font-size:32px;margin:10px;" class="icon-ungroup" />
    <i style="font-size:32px;margin:10px;" class="icon-vector" />
    <i style="font-size:32px;margin:10px;" class="icon-vector2" />
    <i style="font-size:32px;margin:10px;" class="icon-rulers" />
    <i style="font-size:32px;margin:10px;" class="icon-pencil-ruler" />
    <i style="font-size:32px;margin:10px;" class="icon-scissors" />
    <i style="font-size:32px;margin:10px;" class="icon-filter3" />
    <i style="font-size:32px;margin:10px;" class="icon-filter4" />
    <i style="font-size:32px;margin:10px;" class="icon-font" />
    <i style="font-size:32px;margin:10px;" class="icon-ampersand2" />
    <i style="font-size:32px;margin:10px;" class="icon-ligature" />
    <i style="font-size:32px;margin:10px;" class="icon-font-size" />
    <i style="font-size:32px;margin:10px;" class="icon-typography" />
    <i style="font-size:32px;margin:10px;" class="icon-text-height" />
    <i style="font-size:32px;margin:10px;" class="icon-text-width" />
    <i style="font-size:32px;margin:10px;" class="icon-height2" />
    <i style="font-size:32px;margin:10px;" class="icon-width" />
    <i style="font-size:32px;margin:10px;" class="icon-strikethrough2" />
    <i style="font-size:32px;margin:10px;" class="icon-font-size2" />
    <i style="font-size:32px;margin:10px;" class="icon-bold2" />
    <i style="font-size:32px;margin:10px;" class="icon-underline2" />
    <i style="font-size:32px;margin:10px;" class="icon-italic2" />
    <i style="font-size:32px;margin:10px;" class="icon-strikethrough3" />
    <i style="font-size:32px;margin:10px;" class="icon-omega" />
    <i style="font-size:32px;margin:10px;" class="icon-sigma" />
    <i style="font-size:32px;margin:10px;" class="icon-nbsp" />
    <i style="font-size:32px;margin:10px;" class="icon-page-break" />
    <i style="font-size:32px;margin:10px;" class="icon-page-break2" />
    <i style="font-size:32px;margin:10px;" class="icon-superscript" />
    <i style="font-size:32px;margin:10px;" class="icon-subscript" />
    <i style="font-size:32px;margin:10px;" class="icon-superscript2" />
    <i style="font-size:32px;margin:10px;" class="icon-subscript2" />
    <i style="font-size:32px;margin:10px;" class="icon-text-color" />
    <i style="font-size:32px;margin:10px;" class="icon-highlight" />
    <i style="font-size:32px;margin:10px;" class="icon-pagebreak" />
    <i style="font-size:32px;margin:10px;" class="icon-clear-formatting" />
    <i style="font-size:32px;margin:10px;" class="icon-table" />
    <i style="font-size:32px;margin:10px;" class="icon-table2" />
    <i style="font-size:32px;margin:10px;" class="icon-insert-template" />
    <i style="font-size:32px;margin:10px;" class="icon-pilcrow" />
    <i style="font-size:32px;margin:10px;" class="icon-ltr" />
    <i style="font-size:32px;margin:10px;" class="icon-rtl" />
    <i style="font-size:32px;margin:10px;" class="icon-ltr2" />
    <i style="font-size:32px;margin:10px;" class="icon-rtl2" />
    <i style="font-size:32px;margin:10px;" class="icon-section" />
    <i style="font-size:32px;margin:10px;" class="icon-paragraph-left2" />
    <i style="font-size:32px;margin:10px;" class="icon-paragraph-center2" />
    <i style="font-size:32px;margin:10px;" class="icon-paragraph-right2" />
    <i style="font-size:32px;margin:10px;" class="icon-paragraph-justify2" />
    <i style="font-size:32px;margin:10px;" class="icon-indent-increase" />
    <i style="font-size:32px;margin:10px;" class="icon-indent-decrease" />
    <i style="font-size:32px;margin:10px;" class="icon-paragraph-left3" />
    <i style="font-size:32px;margin:10px;" class="icon-paragraph-center3" />
    <i style="font-size:32px;margin:10px;" class="icon-paragraph-right3" />
    <i style="font-size:32px;margin:10px;" class="icon-paragraph-justify3" />
    <i style="font-size:32px;margin:10px;" class="icon-indent-increase2" />
    <i style="font-size:32px;margin:10px;" class="icon-indent-decrease2" />
    <i style="font-size:32px;margin:10px;" class="icon-share" />
    <i style="font-size:32px;margin:10px;" class="icon-share2" />
    <i style="font-size:32px;margin:10px;" class="icon-new-tab" />
    <i style="font-size:32px;margin:10px;" class="icon-new-tab2" />
    <i style="font-size:32px;margin:10px;" class="icon-popout" />
    <i style="font-size:32px;margin:10px;" class="icon-embed" />
    <i style="font-size:32px;margin:10px;" class="icon-embed2" />
    <i style="font-size:32px;margin:10px;" class="icon-markup" />
    <i style="font-size:32px;margin:10px;" class="icon-regexp" />
    <i style="font-size:32px;margin:10px;" class="icon-regexp2" />
    <i style="font-size:32px;margin:10px;" class="icon-code" />
    <i style="font-size:32px;margin:10px;" class="icon-circle-css" />
    <i style="font-size:32px;margin:10px;" class="icon-circle-code" />
    <i style="font-size:32px;margin:10px;" class="icon-terminal" />
    <i style="font-size:32px;margin:10px;" class="icon-unicode" />
    <i style="font-size:32px;margin:10px;" class="icon-seven-segment-0" />
    <i style="font-size:32px;margin:10px;" class="icon-seven-segment-1" />
    <i style="font-size:32px;margin:10px;" class="icon-seven-segment-2" />
    <i style="font-size:32px;margin:10px;" class="icon-seven-segment-3" />
    <i style="font-size:32px;margin:10px;" class="icon-seven-segment-4" />
    <i style="font-size:32px;margin:10px;" class="icon-seven-segment-5" />
    <i style="font-size:32px;margin:10px;" class="icon-seven-segment-6" />
    <i style="font-size:32px;margin:10px;" class="icon-seven-segment-7" />
    <i style="font-size:32px;margin:10px;" class="icon-seven-segment-8" />
    <i style="font-size:32px;margin:10px;" class="icon-seven-segment-9" />
    <i style="font-size:32px;margin:10px;" class="icon-share3" />
    <i style="font-size:32px;margin:10px;" class="icon-share4" />
    <i style="font-size:32px;margin:10px;" class="icon-google" />
    <i style="font-size:32px;margin:10px;" class="icon-google-plus" />
    <i style="font-size:32px;margin:10px;" class="icon-google-plus2" />
    <i style="font-size:32px;margin:10px;" class="icon-google-drive" />
    <i style="font-size:32px;margin:10px;" class="icon-facebook" />
    <i style="font-size:32px;margin:10px;" class="icon-facebook2" />
    <i style="font-size:32px;margin:10px;" class="icon-instagram" />
    <i style="font-size:32px;margin:10px;" class="icon-twitter" />
    <i style="font-size:32px;margin:10px;" class="icon-twitter2" />
    <i style="font-size:32px;margin:10px;" class="icon-feed2" />
    <i style="font-size:32px;margin:10px;" class="icon-feed3" />
    <i style="font-size:32px;margin:10px;" class="icon-youtube" />
    <i style="font-size:32px;margin:10px;" class="icon-youtube2" />
    <i style="font-size:32px;margin:10px;" class="icon-youtube3" />
    <i style="font-size:32px;margin:10px;" class="icon-vimeo" />
    <i style="font-size:32px;margin:10px;" class="icon-vimeo2" />
    <i style="font-size:32px;margin:10px;" class="icon-lanyrd" />
    <i style="font-size:32px;margin:10px;" class="icon-flickr" />
    <i style="font-size:32px;margin:10px;" class="icon-flickr2" />
    <i style="font-size:32px;margin:10px;" class="icon-flickr3" />
    <i style="font-size:32px;margin:10px;" class="icon-picassa" />
    <i style="font-size:32px;margin:10px;" class="icon-picassa2" />
    <i style="font-size:32px;margin:10px;" class="icon-dribbble" />
    <i style="font-size:32px;margin:10px;" class="icon-dribbble2" />
    <i style="font-size:32px;margin:10px;" class="icon-dribbble3" />
    <i style="font-size:32px;margin:10px;" class="icon-forrst" />
    <i style="font-size:32px;margin:10px;" class="icon-forrst2" />
    <i style="font-size:32px;margin:10px;" class="icon-deviantart" />
    <i style="font-size:32px;margin:10px;" class="icon-deviantart2" />
    <i style="font-size:32px;margin:10px;" class="icon-steam" />
    <i style="font-size:32px;margin:10px;" class="icon-steam2" />
    <i style="font-size:32px;margin:10px;" class="icon-dropbox" />
    <i style="font-size:32px;margin:10px;" class="icon-onedrive" />
    <i style="font-size:32px;margin:10px;" class="icon-github" />
    <i style="font-size:32px;margin:10px;" class="icon-github4" />
    <i style="font-size:32px;margin:10px;" class="icon-github5" />
    <i style="font-size:32px;margin:10px;" class="icon-wordpress" />
    <i style="font-size:32px;margin:10px;" class="icon-wordpress2" />
    <i style="font-size:32px;margin:10px;" class="icon-joomla" />
    <i style="font-size:32px;margin:10px;" class="icon-blogger" />
    <i style="font-size:32px;margin:10px;" class="icon-blogger2" />
    <i style="font-size:32px;margin:10px;" class="icon-tumblr" />
    <i style="font-size:32px;margin:10px;" class="icon-tumblr2" />
    <i style="font-size:32px;margin:10px;" class="icon-yahoo" />
    <i style="font-size:32px;margin:10px;" class="icon-tux" />
    <i style="font-size:32px;margin:10px;" class="icon-apple2" />
    <i style="font-size:32px;margin:10px;" class="icon-finder" />
    <i style="font-size:32px;margin:10px;" class="icon-android" />
    <i style="font-size:32px;margin:10px;" class="icon-windows" />
    <i style="font-size:32px;margin:10px;" class="icon-windows8" />
    <i style="font-size:32px;margin:10px;" class="icon-soundcloud" />
    <i style="font-size:32px;margin:10px;" class="icon-soundcloud2" />
    <i style="font-size:32px;margin:10px;" class="icon-skype" />
    <i style="font-size:32px;margin:10px;" class="icon-reddit" />
    <i style="font-size:32px;margin:10px;" class="icon-linkedin" />
    <i style="font-size:32px;margin:10px;" class="icon-linkedin2" />
    <i style="font-size:32px;margin:10px;" class="icon-lastfm" />
    <i style="font-size:32px;margin:10px;" class="icon-lastfm2" />
    <i style="font-size:32px;margin:10px;" class="icon-delicious" />
    <i style="font-size:32px;margin:10px;" class="icon-stumbleupon" />
    <i style="font-size:32px;margin:10px;" class="icon-stumbleupon2" />
    <i style="font-size:32px;margin:10px;" class="icon-stackoverflow" />
    <i style="font-size:32px;margin:10px;" class="icon-pinterest2" />
    <i style="font-size:32px;margin:10px;" class="icon-xing" />
    <i style="font-size:32px;margin:10px;" class="icon-flattr" />
    <i style="font-size:32px;margin:10px;" class="icon-foursquare" />
    <i style="font-size:32px;margin:10px;" class="icon-paypal" />
    <i style="font-size:32px;margin:10px;" class="icon-paypal2" />
    <i style="font-size:32px;margin:10px;" class="icon-yelp" />
    <i style="font-size:32px;margin:10px;" class="icon-file-pdf" />
    <i style="font-size:32px;margin:10px;" class="icon-file-openoffice" />
    <i style="font-size:32px;margin:10px;" class="icon-file-word" />
    <i style="font-size:32px;margin:10px;" class="icon-file-excel" />
    <i style="font-size:32px;margin:10px;" class="icon-libreoffice" />
    <i style="font-size:32px;margin:10px;" class="icon-html5" />
    <i style="font-size:32px;margin:10px;" class="icon-html52" />
    <i style="font-size:32px;margin:10px;" class="icon-css3" />
    <i style="font-size:32px;margin:10px;" class="icon-git" />
    <i style="font-size:32px;margin:10px;" class="icon-svg" />
    <i style="font-size:32px;margin:10px;" class="icon-codepen" />
    <i style="font-size:32px;margin:10px;" class="icon-chrome" />
    <i style="font-size:32px;margin:10px;" class="icon-firefox" />
    <i style="font-size:32px;margin:10px;" class="icon-IE" />
    <i style="font-size:32px;margin:10px;" class="icon-opera" />
    <i style="font-size:32px;margin:10px;" class="icon-safari" />
    <i style="font-size:32px;margin:10px;" class="icon-check2" />
    <i style="font-size:32px;margin:10px;" class="icon-home4" />
    <i style="font-size:32px;margin:10px;" class="icon-people" />
    <i style="font-size:32px;margin:10px;" class="icon-checkmark-circle2" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-up-left32" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-up52" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-up-right32" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-right6" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-down-right32" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-down52" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-down-left32" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-left52" />
    <i style="font-size:32px;margin:10px;" class="icon-calendar5" />
    <i style="font-size:32px;margin:10px;" class="icon-move-alt1" />
    <i style="font-size:32px;margin:10px;" class="icon-reload-alt" />
    <i style="font-size:32px;margin:10px;" class="icon-move-vertical" />
    <i style="font-size:32px;margin:10px;" class="icon-move-horizontal" />
    <i style="font-size:32px;margin:10px;" class="icon-hash" />
    <i style="font-size:32px;margin:10px;" class="icon-bars-alt" />
    <i style="font-size:32px;margin:10px;" class="icon-eye8" />
    <i style="font-size:32px;margin:10px;" class="icon-search4" />
    <i style="font-size:32px;margin:10px;" class="icon-zoomin3" />
    <i style="font-size:32px;margin:10px;" class="icon-zoomout3" />
    <i style="font-size:32px;margin:10px;" class="icon-add" />
    <i style="font-size:32px;margin:10px;" class="icon-subtract" />
    <i style="font-size:32px;margin:10px;" class="icon-exclamation" />
    <i style="font-size:32px;margin:10px;" class="icon-question6" />
    <i style="font-size:32px;margin:10px;" class="icon-close2" />
    <i style="font-size:32px;margin:10px;" class="icon-task" />
    <i style="font-size:32px;margin:10px;" class="icon-inbox" />
    <i style="font-size:32px;margin:10px;" class="icon-inbox-alt" />
    <i style="font-size:32px;margin:10px;" class="icon-envelope" />
    <i style="font-size:32px;margin:10px;" class="icon-compose" />
    <i style="font-size:32px;margin:10px;" class="icon-newspaper2" />
    <i style="font-size:32px;margin:10px;" class="icon-calendar22" />
    <i style="font-size:32px;margin:10px;" class="icon-hyperlink" />
    <i style="font-size:32px;margin:10px;" class="icon-trash" />
    <i style="font-size:32px;margin:10px;" class="icon-trash-alt" />
    <i style="font-size:32px;margin:10px;" class="icon-grid5" />
    <i style="font-size:32px;margin:10px;" class="icon-grid-alt" />
    <i style="font-size:32px;margin:10px;" class="icon-menu6" />
    <i style="font-size:32px;margin:10px;" class="icon-list3" />
    <i style="font-size:32px;margin:10px;" class="icon-gallery" />
    <i style="font-size:32px;margin:10px;" class="icon-calculator" />
    <i style="font-size:32px;margin:10px;" class="icon-windows2" />
    <i style="font-size:32px;margin:10px;" class="icon-browser" />
    <i style="font-size:32px;margin:10px;" class="icon-portfolio" />
    <i style="font-size:32px;margin:10px;" class="icon-comments" />
    <i style="font-size:32px;margin:10px;" class="icon-screen3" />
    <i style="font-size:32px;margin:10px;" class="icon-iphone" />
    <i style="font-size:32px;margin:10px;" class="icon-ipad" />
    <i style="font-size:32px;margin:10px;" class="icon-googleplus5" />
    <i style="font-size:32px;margin:10px;" class="icon-pin" />
    <i style="font-size:32px;margin:10px;" class="icon-pin-alt" />
    <i style="font-size:32px;margin:10px;" class="icon-cog5" />
    <i style="font-size:32px;margin:10px;" class="icon-graduation" />
    <i style="font-size:32px;margin:10px;" class="icon-air" />
    <i style="font-size:32px;margin:10px;" class="icon-droplets" />
    <i style="font-size:32px;margin:10px;" class="icon-statistics" />
    <i style="font-size:32px;margin:10px;" class="icon-pie5" />
    <i style="font-size:32px;margin:10px;" class="icon-cross" />
    <i style="font-size:32px;margin:10px;" class="icon-minus2" />
    <i style="font-size:32px;margin:10px;" class="icon-plus2" />
    <i style="font-size:32px;margin:10px;" class="icon-info3" />
    <i style="font-size:32px;margin:10px;" class="icon-info22" />
    <i style="font-size:32px;margin:10px;" class="icon-question7" />
    <i style="font-size:32px;margin:10px;" class="icon-help" />
    <i style="font-size:32px;margin:10px;" class="icon-warning2" />
    <i style="font-size:32px;margin:10px;" class="icon-add-to-list" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-left12" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-down12" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-up12" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-right13" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-left22" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-down22" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-up22" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-right22" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-left32" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-down32" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-up32" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-right32" />
    <i style="font-size:32px;margin:10px;" class="icon-switch2" />
    <i style="font-size:32px;margin:10px;" class="icon-checkmark5" />
    <i style="font-size:32px;margin:10px;" class="icon-ampersand" />
    <i style="font-size:32px;margin:10px;" class="icon-alert" />
    <i style="font-size:32px;margin:10px;" class="icon-alignment-align" />
    <i style="font-size:32px;margin:10px;" class="icon-alignment-aligned-to" />
    <i style="font-size:32px;margin:10px;" class="icon-alignment-unalign" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-down132" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-up13" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-left13" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-right14" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-small-down" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-small-left" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-small-right" />
    <i style="font-size:32px;margin:10px;" class="icon-arrow-small-up" />
    <i style="font-size:32px;margin:10px;" class="icon-check" />
    <i style="font-size:32px;margin:10px;" class="icon-chevron-down" />
    <i style="font-size:32px;margin:10px;" class="icon-chevron-left" />
    <i style="font-size:32px;margin:10px;" class="icon-chevron-right" />
    <i style="font-size:32px;margin:10px;" class="icon-chevron-up" />
    <i style="font-size:32px;margin:10px;" class="icon-clippy" />
    <i style="font-size:32px;margin:10px;" class="icon-comment" />
    <i style="font-size:32px;margin:10px;" class="icon-comment-discussion" />
    <i style="font-size:32px;margin:10px;" class="icon-dash" />
    <i style="font-size:32px;margin:10px;" class="icon-diff" />
    <i style="font-size:32px;margin:10px;" class="icon-diff-added" />
    <i style="font-size:32px;margin:10px;" class="icon-diff-ignored" />
    <i style="font-size:32px;margin:10px;" class="icon-diff-modified" />
    <i style="font-size:32px;margin:10px;" class="icon-diff-removed" />
    <i style="font-size:32px;margin:10px;" class="icon-diff-renamed" />
    <i style="font-size:32px;margin:10px;" class="icon-file-media" />
    <i style="font-size:32px;margin:10px;" class="icon-fold" />
    <i style="font-size:32px;margin:10px;" class="icon-gear" />
    <i style="font-size:32px;margin:10px;" class="icon-git-branch" />
    <i style="font-size:32px;margin:10px;" class="icon-git-commit" />
    <i style="font-size:32px;margin:10px;" class="icon-git-compare" />
    <i style="font-size:32px;margin:10px;" class="icon-git-merge" />
    <i style="font-size:32px;margin:10px;" class="icon-git-pull-request" />
    <i style="font-size:32px;margin:10px;" class="icon-graph" />
    <i style="font-size:32px;margin:10px;" class="icon-law" />
    <i style="font-size:32px;margin:10px;" class="icon-list-ordered" />
    <i style="font-size:32px;margin:10px;" class="icon-list-unordered" />
    <i style="font-size:32px;margin:10px;" class="icon-mail5" />
    <i style="font-size:32px;margin:10px;" class="icon-mail-read" />
    <i style="font-size:32px;margin:10px;" class="icon-mention" />
    <i style="font-size:32px;margin:10px;" class="icon-mirror" />
    <i style="font-size:32px;margin:10px;" class="icon-move-down" />
    <i style="font-size:32px;margin:10px;" class="icon-move-left" />
    <i style="font-size:32px;margin:10px;" class="icon-move-right" />
    <i style="font-size:32px;margin:10px;" class="icon-move-up" />
    <i style="font-size:32px;margin:10px;" class="icon-person" />
    <i style="font-size:32px;margin:10px;" class="icon-plus22" />
    <i style="font-size:32px;margin:10px;" class="icon-primitive-dot" />
    <i style="font-size:32px;margin:10px;" class="icon-primitive-square" />
    <i style="font-size:32px;margin:10px;" class="icon-repo-forked" />
    <i style="font-size:32px;margin:10px;" class="icon-screen-full" />
    <i style="font-size:32px;margin:10px;" class="icon-screen-normal" />
    <i style="font-size:32px;margin:10px;" class="icon-sync" />
    <i style="font-size:32px;margin:10px;" class="icon-three-bars" />
    <i style="font-size:32px;margin:10px;" class="icon-unfold" />
    <i style="font-size:32px;margin:10px;" class="icon-versions" />
    <i style="font-size:32px;margin:10px;" class="icon-x" />
  </div>
</template>

<script>
export default {
  data() {
    return {};
  }
};
</script>
